<a href="https://colab.research.google.com/github/junonnnnn/data-science-toolkit/blob/main/python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print("Welcome to Data Science")

Welcome to Data Science


In [4]:
x = 5
print("Value of x is: ", x)
print(type(x))

Value of x is:  5
<class 'int'>


In [5]:
y = "I am Yong Jun Onn"
print(y)

I am Yong Jun Onn


In [7]:
a = []
a.append(y)
a[0][1]

' '

In [8]:
b = str.split(y)
b[4]

'Onn'

In [9]:
import numpy as np
a = []
for i in range(1, 11):
    a.append(i)
b = np.array(a)
b[3]

np.int64(4)

In [10]:
!python --version


Python 3.12.12


In [12]:
print(f"Hi, {y}")

Hi, I am Yong Jun Onn


In [13]:
alt = '{}'.format(y)
print(alt)

I am Yong Jun Onn


In [15]:
num1 = a[2]

print(f"The 3rd number in list a is {str(a[2])}")

The 3rd number in list a is 3


In [16]:
list1 = [1, 2, 3, 4, 5]
list1.pop()
print(list1)

[1, 2, 3, 4]


In [25]:
numbers = list(range(6))
print(numbers)
print(numbers[2:])
numbers[2:4] = [10, 20]
print(numbers)

[0, 1, 2, 3, 4, 5]
[2, 3, 4, 5]
[0, 1, 10, 20, 4, 5]


In [28]:
dict = {'cat': 'cute', 'dog': 'furry'}
print(dict['cat'])
print('cat' in dict)

cute
True


In [39]:
array1 = np.array([1, 2, 3])
print(type(array1), array1.shape)
array2 = np.array([4, 5, 6])
stack1 = np.stack((array1, array2))
print(stack1, stack1.shape)


<class 'numpy.ndarray'> (3,)
[[1 2 3]
 [4 5 6]] (2, 3)


In [42]:
stack2 = np.stack((array1, array2), axis=0)
print(stack2, stack2.shape)
#alternative
print(stack2[1,2])

[[1 2 3]
 [4 5 6]] (2, 3)
6


In [44]:
n1 = np.ones((1,2))
n1

array([[1., 1.]])

In [45]:
n2 = np.ones((2,2))
n2

array([[1., 1.],
       [1., 1.]])

In [47]:
n3 = np.full((2,2), 7)
n3

array([[7, 7],
       [7, 7]])

In [48]:
n4 = np.eye(3)
n4
# Identity Matrices

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
n5 = np.random.random((2,2))
n5

array([[0.99678394, 0.39760297],
       [0.14938748, 0.72958391]])

In [50]:
print(n5[1, :])

[0.14938748 0.72958391]
