In [ ]:
import numpy as np

In [ ]:
q1 = np.array([(1, 2), (3,4)])
q1


array([[1, 2],
       [3, 4]])

In [ ]:
q2 = np.random.random((3,4))
q2

array([[0.41907051, 0.60667883, 0.77193915, 0.47891544],
       [0.47647609, 0.04701496, 0.79915136, 0.27532828],
       [0.15224165, 0.18121503, 0.38511614, 0.82179691]])

In [ ]:
q3a = np.ones((2, 2))
q3b = np.zeros((2, 2))
q3a, q3b

(array([[1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.]]))

In [ ]:
q4a = np.random.random((6, 3))
q4b = np.transpose(q4a)
print(f"Initial array is \n{q4a}, \ntransposed array is \n{q4b}")

Initial array is 
[[0.40917966 0.03051461 0.59890893]
 [0.52518442 0.1539024  0.31904858]
 [0.65247724 0.38826127 0.22440545]
 [0.97873052 0.46277066 0.81044544]
 [0.42384281 0.99501664 0.59682575]
 [0.72007438 0.54216532 0.08286116]], 
transposed array is 
[[0.40917966 0.52518442 0.65247724 0.97873052 0.42384281 0.72007438]
 [0.03051461 0.1539024  0.38826127 0.46277066 0.99501664 0.54216532]
 [0.59890893 0.31904858 0.22440545 0.81044544 0.59682575 0.08286116]]


In [ ]:
q5a = np.random.random((2, 3))
q5b = np.random.random((3, 4))
dot_product = np.dot(q5a, q5b)
dot_product

array([[0.72779777, 0.50495475, 0.5296399 , 0.37108144],
       [0.81815636, 0.52760954, 0.55984629, 0.44615377]])

In [35]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/git_repos/data-science-toolkit

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/git_repos/data-science-toolkit
